### ISSUE TITLE
Reloading the Integration creates everything anew

### ISSUE THREAD

**Issue by doctorkb** [twrecked/hass-virtual#93]
When I restart Home Assistant, it behaves as expected, making appropriate changes to the entities.
However, when I just reload the integration, it forgets everything from before and creates new entities

**Comment by twrecked** [comment]
Which version are you on?

**Comment by doctorkb** [comment]
Virtual Components 0.9.0a6, HAss Core 2024.1.6

**Comment by twrecked** [comment]
Can you try the latest build? I might have been using the wrong directory during upgrades.

**Comment by doctorkb** [comment]
Just tried 0.9.0a9 -- it still recreates the entities with new names.

This occurs when I go to the Virtual Devices integration, then select the three dots next to "Imported Virtual Group" and select "Reload".

**Comment by frankfrommelt** [comment]
Same for me even with the latest build b10.
Whenever I press "reload" a new round of entities is created (_2, _3, _4, ...).
When rebooting the HA (I just updated core) no new entities are created.

**Comment by twrecked** [comment]
Found it. I'd forgotten the to remove on reload. I'll test and push a fix.

**Comment by frankfrommelt** [comment]
OK, in v 0.9.0b11 a reload does not create the counting _2, _3, _4, ... entities any more.
So, in general we should considers this bug as being fixed.
Thank you.
Sadly, for me, it re-created all the virtual.xyz_3 entities I had as virtual.xyz entities (removing the numbering on re-load).
So, no I have to touch all the automations etc. none more (hopefully last) time...

**Comment by twrecked** [comment]
Yes. I pushed a possible fix but I've been busy all weekend and didn't get a chance to update any issues. 

I had to delete and reload my devices to revert my naming after verifying and then testing the fix. Not ideal I'm sorry.

**Comment by ildar170975** [comment]
Just updated to the latest 0.9.0.beta.11 from 0.8.x & started testing.
Noticed this behaviour, probably related to the current issue:
1. Open some Light device.
2. Associate it with some area.
3. Make some changes in "virtual.yaml".
4. Reload config entry.
5. See that this device is again not associated with an area.

**Comment by dawon** [comment]
I don't have to change anything in the config, just doing config reload removes area, friendly name and history of all entities.

Version: 0.9.0b17

**Comment by dawon** [comment]
Just plain reloading of the config without any changes does reset friendly names and areas of all entities... 

0.9.0.beta.17

**Comment by JeremiePlam** [comment]
This is still a problem in 0.9.2
Reloading the integration or restarting Home Assistant creates a new copy of my virtual lights. The original ones become "unavailable" and the new ones get new entity IDs, which breaks my automations.

To work around the issue, I have to manually delete the old "unavailable" entities and rename the IDs of the new lights to the IDs of the old lights.

**Comment by frankfrommelt** [comment]
Hi,
I do not have the issue any more, I can reload the integration or restart HA as often as I want and have always the same entities.
Can you post your virtual.yaml?
Maybe the reason for the issue is there.

**Comment by JeremiePlam** [comment]
```
Virtual Lighting:
- platform: light
  support_brightness: true
  support_color: true
  support_color_temp: true
- platform: switch
```

**Comment by frankfrommelt** [comment]
OK, looks different to mine...

version: 1
devices:
  +KuK:
    - platform: light
      name: +KuK
      initial_value: "off"
      support_brightness: false
      support_color: false
      support_color_temp: false
      support_white_value: false
      initial_brightness: 255
      unique_id: NOTYET
      support_effect: false
      device_id: NOTYET
      initial_white_value: 240
      initial_color:
        - 0
        - 100
      initial_effect_list:
        - rainbow
        - none
      initial_availability: true
      initial_color_temp: 240
      persistent: true
      initial_effect: none
      entity_id: NOTYET
  +Waschmaschine:
    - platform: switch
      name: +Waschmaschine
      initial_value: "off"
  +Spülmaschine:
    - platform: switch
      name: +Spülmaschine
      initial_value: "off"
  +Solarstrom:
    - platform: switch
      name: +Solarstrom
      initial_value: "off"
  +Trockner:
    - platform: switch
      name: +Trockner
      initial_value: "off"
  +Wärmepumpe:
    - platform: switch
      name: +Wärmepumpe
      initial_value: "off"
  +PVWärmepumpe:
    - platform: switch
      name: +PVWärmepumpe
      initial_value: "off"
  +Heimurlaub:
    - platform: switch
      name: +Heimurlaub
      initial_value: "off"
  +Urlaub:
    - platform: switch
      name: +Urlaub
      initial_value: "off"
  +Unterwegs:
    - platform: switch
      name: +Unterwegs
      initial_value: "off"
  +Sonnenschutz:
    - platform: switch
      name: +Sonnenschutz
      initial_value: "off"
  +Nachtlüften:
    - platform: switch
      name: +Nachtlüften
      initial_value: "off"
  +Fusspflege:
    - platform: light
      name: +Fusspflege
      initial_value: "off"
  +Heizperiode:
    - platform: switch
      name: +Heizperiode
      initial_value: "on"


--- Original Nachricht ---
Von: JeremiePlam ***@***.***
Datum: 18. Mai 2025 14:51:18
An: twrecked/hass-virtual ***@***.***
CC: Frank Frommelt ***@***.***, Comment ***@***.***
Betreff: Re: [twrecked/hass-virtual] Reloading the Integration creates 
everything anew (Issue #93)

**Comment by twrecked** [comment]
@JeremiePlam Nice find. I'll take a look at why that is.

**Comment by dlakatos847** [comment]
Using `v0.9.3`, issue is still present. This might help finding the bug.

Removed the integration, cleaned the SQLite database, stopped the core container, cleaned all relevant `/config/.storage` files, started the core container, imported the following single yaml file (attachment did not work for some reason).

`/config/virtual.yaml`
```
andrea_device_tracker:
  - platform: device_tracker
    initial_value: iroda
Hall Heating Switch:
  - platform: switch
    name: hall_heating
Hall Cooling Switch:
  - platform: switch
    name: hall_cooling
Bathroom Heating Switch:
  - platform: switch
    name: bathroom_heating
Bathroom Cooling Switch:
  - platform: switch
    name: bathroom_cooling
Bathroom Fan:
  - platform: fan
    name: bathroom
Bedroom Heating Switch:
  - platform: switch
    name: bedroom_heating
Bedroom Cooling Switch:
  - platform: switch
    name: bedroom_cooling
Bedroom HRV:
  - platform: fan
    name: bedroomhrv
    speed: True
    speed_count: 5
    direction: True
    oscillate: True
Common Area Heating Switch:
  - platform: switch
    name: commonarea_heating
Common Area Cooling Switch:
  - platform: switch
    name: commonarea_cooling
Hall Light:
  - platform: light
    name: hall
Bathroom Light:
  - platform: light
    name: bathroom
Bedroom Light:
  - platform: light
    name: bedroom
Bedroom Shutter:
  - platform: cover
    name: bedroom
    open_close_duration: 25
    open_close_tick: 0.25
    class: shutter
Balcony Light:
  - platform: light
    name: balcony
Livingroom Light:
  - platform: light
    name: livingroom
Livingroom Shutter:
  - platform: cover
    name: livingroom
    open_close_duration: 25
    open_close_tick: 0.25
    class: shutter
Kitchen Light:
  - platform: light
    name: kitchen
Entry Lock:
  - platform: lock
    name: entry
    initial_value: locked
Bedroom Window Sensor:
  - platform: binary_sensor
    name: bedroom_window
    class: window
Livingroom Window Sensor:
  - platform: binary_sensor
    name: livingroom_window
    class: window
```

Everything works fine, until a config reload or reboot.

These appear in the logs after core container reboot:
```
2026-05-16 11:41:34.949 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'virtual' sets an entity ID with wrong domain: 'light.bathroom'. Expected domain is 'fan'. This will stop working in Home Assistant 2027.5.0, please create a bug report at https://github.com/twrecked/hass-virtual/issues
2026-05-16 11:41:34.953 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'virtual' sets an entity ID with wrong domain: 'cover.bedroom'. Expected domain is 'light'. This will stop working in Home Assistant 2027.5.0, please create a bug report at https://github.com/twrecked/hass-virtual/issues
2026-05-16 11:41:34.954 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'virtual' sets an entity ID with wrong domain: 'cover.livingroom'. Expected domain is 'light'. This will stop working in Home Assistant 2027.5.0, please create a bug report at https://github.com/twrecked/hass-virtual/issues
```

I used multiple entities in a single device before. Not sure if the issue left some residual files somewhere.
